name: "Hello Custom Action"
description: "A simple greeting GitHub Actions workflow"

on:
    workflow_dispatch:
        inputs:
            who-to-greet:
                description: "Who to greet"
                required: true
                default: "World"

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Greet
              run: |
                  echo "Hello ${GREET:-${{ github.event.inputs.who-to-greet }}}"
