name: Pipeline for secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: use secrets
        run: |
          echo "Using secrets in this step"
          # Example: access a secret named MY_SECRET
          echo "Secret (masked): ${{ secrets.MY_SECRET }}"
